FROM node:latest AS builder

WORKDIR /app
COPY . .


RUN npm ci


RUN npm run build -- --configuration production


FROM nginx:stable-alpine AS production


RUN rm -rf /usr/share/nginx/html/*


COPY --from=builder /app/dist/inventory-app/browser /usr/share/nginx/html

RUN chmod -R 755 /usr/share/nginx/html


COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
