version: '3'
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  task5backend:
    build: ./backend
    container_name: task5backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/db
    depends_on:
      - mongo

volumes:
  mongo-data:
