version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: InventoryDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Presidio123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./
    container_name: inventorymanagementapi
    depends_on:
      - postgres
    ports:
      - "5085:5000"
      - "5443:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
    networks:
      - backend-net

volumes:
  pgdata:

networks:
  backend-net:
